### ISSUE TITLE
Add support for "on conflict" clause

### ISSUE THREAD

**Issue by rguryanov** [hiro80/miniSqlParser#7]
**概要**
不具合の簡単な概要を記述してください
SQL queries that contain "on conflict"  clause produce errors in the parser (no support in grammar).

**再現方法**
不具合を再現させる手順を教えて下さい
Example query:
```
INSERT INTO users (id, level)
VALUES (1, 0)
ON CONFLICT (id) DO UPDATE
SET level = users.level + 1;
```

**不具合が発生した環境**
 - OS: Windows7
 - Browser  firefox quantum 67.0 (64-bit)

Thank you.

**Comment by hiro80** [comment]
The miniSqlParser has supported DO UPDATE clause in INSERT statement that used in the PostgreSQL  !! (384542da8256a24d3d944f247b9802f5a5afd1b3).
@rguryanov Please confirm it. If it fixed completely, could you close this issue?
