### ISSUE TITLE
MERGE statement error.

### ISSUE THREAD

**Issue by rguryanov** [hiro80/miniSqlParser#8]
**概要**
不具合の簡単な概要を記述してください
Sql query that use MERGE (T-Sql) produce errors in the parser ("into" part is optional and not written in query). 

**再現方法**
不具合を再現させる手順を教えて下さい
Example query:

```
MERGE 
   member_topic AS target
USING 
   someOtherTable AS source
ON 
   target.mt_member = source.mt_member 
   AND source.mt_member = 0 
   AND source.mt_topic = 110
WHEN MATCHED THEN 
   UPDATE SET mt_notes = 'test'
WHEN NOT MATCHED THEN 
   INSERT (mt_member, mt_topic, mt_notes) VALUES (0, 110, 'test')
```

**不具合が発生した環境**
 - OS: Windows7
 - Browser firefox quantum 67.0 (64-bit)

Thank you.

**Comment by hiro80** [comment]
The INTO keyword of the merge statement has been changed to optional.
 (ab8916fe85a34b4d362c1ef3753722f8f9d309b2)
